### ISSUE TITLE
Could not retrieve tracks 

### ISSUE THREAD

**Issue by zuxa** [Otiel/SoundCloudDownloader#2]
hi
when i try download something from cs i have this:
![2016-09-06_121012](https://cloud.githubusercontent.com/assets/22024372/18268378/821a1194-7434-11e6-9b31-16cf49fc9044.png)
i`m using 0.1.2.1 Apr 17, 2014
this version working now?

**Comment by Otiel** [comment]
Hi,

Unfortunately, this application is not working anymore since SoundCloud made huge changes to their website. I should point it out on the home page of the project...
